setwd("~/Coursera/Exploratory Data Analysis")
household_power_consumption<- read.table(unz("exdata_data_household_power_consumption.zip", "household_power_consumption.txt"), header=T, quote="\"", sep=";",na.strings = "?")
memory_Roughly<-nrow(household_power_consumption)*ncol(household_power_consumption)*8
memory_Roughly<-memory_Roughly/2^20
memory_Roughly<-paste(round(memory_Roughly,2), "Mb",sep = " ")
memory_Roughly
household_power_consumption$Convert <- strptime(paste(household_power_consumption$Date, household_power_consumption$Time), "%d/%m/%Y %H:%M:%S")
household_power_consumption$Date <- as.Date(household_power_consumption$Date, "%d/%m/%Y")
class(household_power_consumption$Date)
Selected_household_temp <- subset(household_power_consumption, Date >= as.Date("2007-02-15") & Date <= as.Date("2007-02-16"))
png(file="plot4.png", width=480, height=480)
par(mfrow=c(2,2))
par(mar=c(4,4,1,1))
plot(Selected_household_temp$Convert, Selected_household_temp$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(Selected_household_temp$Convert, Selected_household_temp$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(Selected_household_temp$Convert, Selected_household_temp$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(Selected_household_temp$Convert, Selected_household_temp$Sub_metering_2, type = "l", col = "red")
points(Selected_household_temp$Convert, Selected_household_temp$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(Selected_household_temp$Convert, Selected_household_temp$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global Reactive Power")
dev.off()